### ISSUE TITLE
zio remote cluster authentication and pod listing

### ISSUE THREAD

**Issue by MohammadForouhesh** [hnaderi/scala-k8s#248]
Hi @hnaderi, documentation for listing pods (simplest example) in zio when we have a remote cluster is missing. the following code was the best I came up with. 

```
object Main extends ZIOAppDefault {
  def run = {
    val token = "sha256~xxxx"

    val namespace = "my-namespace"
    val host = "https://cluster_url:443"
    val auth = AuthenticationParams.bearer(token)

    val client = ZClient.default
    val backend = ZIOBackend.make
    val k8sLayer = ZLayer.fromFunction(HttpClient[Task](host, _, auth))
    (for {
      k8s <- ZIO.service[HttpClient[Task]]
      x <- k8s.send(PodAPI(namespace).list)
      _ <- ZIO.logInfo(x.toString)
    } yield ())
      .provide(
        client,
        backend,
        k8sLayer
      )
}
```

and I encounter the following error:
```
timestamp=2023-12-05 level=ERROR thread=#zio-fiber-1 message="" cause="Exception in thread "zio-fiber-4" dev.hnaderi.k8s.client.ErrorResponse: Request failed!
status: Other(403)
details: Status(Status,v1,Some(Forbidden),Some(403),Some(Failure),Some(StatusDetails(None,None,None,Some(pods),None,None)),Some(ListMeta(None,None,None,None)),Some(pods is forbidden: User "system:anonymous" cannot list resource "pods" in API group "" in the namespace "my-namespace"))

        at dev.hnaderi.k8s.client.ZIOBackend.$anonfun$expect$5(ZIOBackend.scala:137)
        at zio.ZIO.$anonfun$map$2(ZIO.scala:960)
        at dev.hnaderi.k8s.client.ZIOBackend.expect(ZIOBackend.scala:137)
        at testK8s.Main.run.client(main.scala:50)
        at testK8s.Main.run(main.scala:65)"
```

any help will be highly appreciated.

**Comment by hnaderi** [comment]
Hi @MohammadForouhesh , ZIO module uses ZIO http, which lacks the TLS support required for connecting to kubernetes directly and the 403 error is because of this. 

There are a few different ways you can resolve this problem:

1. Use other modules to connect directly, as the only module that doesn't support TLS is the ZIO module. I recommend http4s if you want a reliable, mature and multi-platform client. You can also use sttp if all you want is simple scripting.
2. Note that if you want to use ZIO as the effect system, you can use http4s module as well, as it is based on cats-effect and is designed in a tagless final way, so you can use any effect system. For using with zio you can use ZIO interop module for cats effect.
3. You can use `kubectl proxy` to get a new server locally that handles the underlying TLS connection and authentication, and then use ZIO client on top of it.

Hope this helps! Let me know if there are any problems or questions.

**Comment by hnaderi** [comment]
If you want to access kubernetes API using service account credentials, the easiest approach would be number 1 or number 2, as the http4s client supports automatic detection of credentials from pod or kubeconfig or from environment variables, exactly like how `kubectl` works.

For third solution, you need to run `kubectl proxy` and use create the ZIO client like this:

```scala
ZIOKubernetesClient.make("http://localhost:8001")
```
See [here](https://projects.hnaderi.dev/scala-k8s/#zio-based-client) for complete example.

For second solution, I will send an example later today, or probably by tomorrow.

**Comment by MohammadForouhesh** [comment]
thanks a lot, it really helped
